{
 "title": "Vuls",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "severity",
    "label": "Severity",
    "query": "label_values(vulns{}, severity)"
   },
   {
    "name": "server",
    "label": "Server",
    "query": "label_values(servers{}, serverName)"
   }
  ]
 },
 "panels": [
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Found CVS, by severity",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 1 },
   "repeat": "severity",
   "targets": [
    {
     "expr": "vuln_severity{severity=\"$severity\"}",
     "legendFormat": "{{severity}}"
    }
   ]
  },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Found CVEs by Severity",
   "type": "graph",
   "gridPos": { "h": 12, "w": 8, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by (severity) (vuln_severity{})",
     "legendFormat": "{{severity}}"
    }
   ]
  },
  {
   "title": "Found CVEs Overview",
   "type": "table",
   "gridPos": { "h": 12, "w": 16, "x": 8, "y": 8 },
   "targets": [
    {
     "expr": "sum by (cveID, severity, fixState, packageName, summary) (vulns{severity!=\"\"})"
    }
   ]
  },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Vulnerabilities per Server",
   "type": "graph",
   "gridPos": { "h": 10, "w": 16, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (serverName) (servers{})",
     "legendFormat": "{{serverName}}"
    },
    { "expr": "sum (servers{})", "legendFormat": "Total" }
   ]
  },
  {
   "title": "Servers overview",
   "type": "table",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 21 },
   "targets": [
    {
     "expr": "sum by (severity, serverName, hostname) (servers{})",
     "legendFormat": "Count"
    }
   ]
  }
 ]
}